sudo: false
language: node_js
cache: 
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm install npm@latest -g
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm publish