sudo: false
language: node_js
cache: 
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - node
before_install:
  - npm i -g npm@latest
before_script:
  - npm install
  - npm prune
script:
  - npm run test
after_success:
  - npm publish